-- ==============================================================================
-- Nepal Flight Tracker - Initial Aviation Schema
-- Target: Supabase (PostgreSQL 15+)
-- Tables: airports, runways, aircraft_specifications, airlines
-- ==============================================================================

-- Enable UUID extension if needed in future
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ------------------------------------------------------------------------------
-- 1. AIRPORTS TABLE
-- Stores global airports with focus on Nepal and surrounding approach airspace.
-- ------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.airports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ident TEXT UNIQUE NOT NULL,                       -- e.g. 'VNKT', 'VNPK', 'VNBW'
    type TEXT,                                       -- 'large_airport', 'medium_airport', 'small_airport', 'heliport'
    name TEXT NOT NULL,                              -- e.g. 'Tribhuvan International Airport'
    latitude_deg DOUBLE PRECISION NOT NULL,          -- Decimal degrees WGS-84
    longitude_deg DOUBLE PRECISION NOT NULL,         -- Decimal degrees WGS-84
    elevation_ft INTEGER,                            -- Elevation in feet above MSL
    continent TEXT DEFAULT 'AS',                     -- Continent code ('AS' for Asia)
    iso_country TEXT DEFAULT 'NP',                   -- ISO 3166-1 alpha-2 ('NP' for Nepal)
    iso_region TEXT,                                 -- e.g. 'NP-BA' (Bagmati)
    municipality TEXT,                               -- City/town e.g. 'Kathmandu', 'Pokhara'
    scheduled_service BOOLEAN DEFAULT FALSE,
    gps_code TEXT,                                   -- GPS code (often same as ident)
    iata_code VARCHAR(3),                            -- 3-letter IATA code e.g. 'KTM', 'PKR', 'BWA'
    local_code TEXT,
    home_link TEXT,
    wikipedia_link TEXT,
    keywords TEXT,
    created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc', NOW()) NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT TIMEZONE('utc', NOW()) NOT NULL
);

-- Indexes for high-frequency airport lookups
CREATE INDEX IF NOT EXISTS idx_airports_ident ON public.airports (ident);
CREATE INDEX IF NOT EXISTS idx_airports_iata ON public.airports (iata_code);
CREATE INDEX IF NOT EXISTS idx_airports_country ON public.airports (iso_country);
CREATE INDEX IF NOT EXISTS idx_airports_coordinates ON public.airports (latitude_deg, longitude_deg);
CREATE INDEX IF NOT EXISTS idx_airports_municipality ON public.airports (municipality);

-- ------------------------------------------------------------------------------
-- 2. RUNWAYS TABLE
-- Stores physical runway dimensions, threshold coordinates, and lighting status.
-- ------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.runways (
    id BIGINT PRIMARY KEY,                           -- Unique runway identifier from dataset
    airport_ref BIGINT,                              -- Reference ID from airport dataset
    airport_ident TEXT NOT NULL REFERENCES public.airports(ident) ON DELETE CASCADE,
    length_ft INTEGER,                               -- Total runway length in feet
    width_ft INTEGER,                                -- Runway width in feet
    surface TEXT,                                    -- 'ASP' (Asphalt), 'CON' (Concrete), 'GRS' (Grass)
    lighted BOOLEAN DEFAULT FALSE,                   -- Has runway lighting
    closed BOOLEAN DEFAULT FALSE,                    -- Is runway closed
    
    -- Low-End (LE) Runway Information
    le_ident TEXT,                                   -- e.g. '02'
    le_latitude_deg DOUBLE PRECISION,
    le_longitude_deg DOUBLE PRECISION,
    le_elevation_ft INTEGER,
    le_heading_degT NUMERIC(5, 1),                   -- True heading
    le_displaced_threshold_ft INTEGER,
    
    -- High-End (HE) Runway Information
    he_ident TEXT,                                   -- e.g. '20'
    he_latitude_deg DOUBLE PRECISION,
    he_longitude_deg DOUBLE PRECISION,
    he_elevation_ft INTEGER,
    he_heading_degT NUMERIC(5, 1),                   -- True heading
    he_displaced_threshold_ft INTEGER,
    
    created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc', NOW()) NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT TIMEZONE('utc', NOW()) NOT NULL
);

-- Indexes for runway queries
CREATE INDEX IF NOT EXISTS idx_runways_airport_ident ON public.runways (airport_ident);
CREATE INDEX IF NOT EXISTS idx_runways_surface ON public.runways (surface);

-- ------------------------------------------------------------------------------
-- 3. AIRCRAFT SPECIFICATIONS TABLE
-- Stores performance characteristics, dimensions, and weights for aircraft models.
-- ------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.aircraft_specifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    model TEXT NOT NULL,                             -- e.g. 'ATR 72-500', 'DHC-6 Twin Otter'
    icao_type VARCHAR(4) NOT NULL,                   -- ICAO designator e.g. 'AT75', 'AT76', 'DHC6', 'A320'
    category TEXT,                                   -- 'Regional', 'Commuter', 'Short/Medium', 'Business', 'General', 'Long Range'
    
    -- Dimensions & Geometry (m, deg, m2)
    fuselage_width NUMERIC(8, 3),                    -- Fuselage outer width (m)
    wing_span NUMERIC(8, 3),                         -- Wing span (m)
    wing_sweep25 NUMERIC(8, 3),                      -- Wing sweep at 25% chord (deg)
    wing_area NUMERIC(8, 3),                         -- Wing reference area (m2)
    wing_position TEXT,                              -- Wing configuration: 'low', 'high'
    htp_area NUMERIC(8, 3),                          -- Horizontal tailplane area (m2)
    vtp_area NUMERIC(8, 3),                          -- Vertical tailplane area (m2)
    total_length NUMERIC(8, 3),                      -- Overall aircraft length (m)
    total_height NUMERIC(8, 3),                      -- Overall aircraft height (m)
    
    -- Weights (in kg)
    oew_kg NUMERIC(10, 2),                           -- Operating Empty Weight (kg)
    owe NUMERIC(10, 2),                              -- OEW alias (kg)
    mtow_kg NUMERIC(10, 2),                          -- Maximum Takeoff Weight (kg)
    mtow NUMERIC(10, 2),                             -- MTOW alias (kg)
    mlw_kg NUMERIC(10, 2),                           -- Maximum Landing Weight (kg)
    mlw NUMERIC(10, 2),                              -- MLW alias (kg)
    fuel_capacity_liters NUMERIC(10, 2),             -- Fuel capacity in liters
    max_fuel NUMERIC(10, 2),                         -- Maximum fuel capacity (kg)
    
    -- Engines & Propulsion
    number_of_engines INTEGER DEFAULT 2,             -- Number of engines
    n_engine INTEGER DEFAULT 2,                      -- Engine count alias
    engine_y_arm NUMERIC(8, 3),                      -- Engine lateral moment arm from centerline (m)
    engine_type TEXT,                                -- Propulsion type: 'Turboprop', 'Turbofan', 'Piston'
    thruster_type TEXT,                              -- Thruster mechanism: 'propeller', 'turbofan'
    engine_model TEXT,                               -- Engine model e.g. 'PW127F', 'PT6A-27'
    powerplant TEXT,                                 -- Powerplant designation e.g. 'Con.TS10-360RB'
    bpr NUMERIC(8, 3),                               -- Bypass ratio (dimensionless)
    energy_type TEXT,                                -- Energy/fuel type: 'gasoline', 'kerosene'
    engine_position TEXT,                            -- Mounting position: 'wing', 'fuselage'
    rotor_diameter NUMERIC(8, 3),                    -- Rotor / propeller diameter (m)
    max_power NUMERIC(10, 2),                        -- Maximum engine power (kW)
    max_power_2 NUMERIC(10, 2),                      -- Secondary maximum engine power (kW)
    max_thrust NUMERIC(12, 2),                       -- Maximum takeoff thrust (N)
    
    -- Capacity, Performance & Speeds
    passenger_capacity INTEGER,                      -- Passenger seating capacity (n_pax)
    cruise_speed_kts INTEGER,                        -- Knots TAS
    max_speed_kts INTEGER,                           -- Knots TAS
    cruise_altitude NUMERIC(10, 2),                  -- Design cruise altitude
    nominal_range_nm INTEGER,                        -- Nautical miles
    approach_speed_kts INTEGER,                      -- Knots IAS
    takeoff_field_length_m INTEGER,                  -- Required takeoff distance in meters (tofl)
    landing_field_length_m INTEGER,                  -- Required landing distance in meters (lfl)
    
    created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc', NOW()) NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT TIMEZONE('utc', NOW()) NOT NULL
);

-- Indexes for aircraft lookups
CREATE INDEX IF NOT EXISTS idx_aircraft_specs_icao ON public.aircraft_specifications (icao_type);
CREATE INDEX IF NOT EXISTS idx_aircraft_specs_model ON public.aircraft_specifications (model);
CREATE INDEX IF NOT EXISTS idx_aircraft_specs_category ON public.aircraft_specifications (category);

-- ------------------------------------------------------------------------------
-- 4. AIRLINES TABLE
-- Reference list of domestic Nepalese carriers and key regional operators.
-- ------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.airlines (
    icao_code VARCHAR(3) PRIMARY KEY,                -- e.g. 'BHA', 'SHA', 'RNA'
    iata_code VARCHAR(2),                            -- e.g. 'U4', 'RA', 'YT'
    name TEXT NOT NULL,                              -- e.g. 'Buddha Air', 'Nepal Airlines'
    callsign TEXT,                                   -- e.g. 'BUDDHA AIR', 'ROYAL NEPAL'
    country TEXT DEFAULT 'Nepal',
    is_domestic BOOLEAN DEFAULT FALSE,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc', NOW()) NOT NULL
);

-- Seed Essential Nepalese Airlines
INSERT INTO public.airlines (icao_code, iata_code, name, callsign, country, is_domestic, is_active)
VALUES
    ('RNA', 'RA', 'Nepal Airlines', 'ROYAL NEPAL', 'Nepal', true, true),
    ('BHA', 'U4', 'Buddha Air', 'BUDDHA AIR', 'Nepal', true, true),
    ('NYT', 'YT', 'Yeti Airlines', 'YETI AIRLINES', 'Nepal', true, true),
    ('SHA', 'N9', 'Shree Airlines', 'SHREE AIR', 'Nepal', true, true),
    ('TRA', 'TB', 'Tara Air', 'TARA AIR', 'Nepal', true, true),
    ('SMT', NULL, 'Summit Air', 'SUMMIT AIR', 'Nepal', true, true),
    ('HRA', 'H9', 'Himalaya Airlines', 'HIMALAYA', 'Nepal', true, true),
    ('GBL', NULL, 'Guna Airlines', 'GUNA AIR', 'Nepal', true, true),
    ('BBC', 'BG', 'Biman Bangladesh Airlines', 'BANGLADESH', 'Bangladesh', false, true),
    ('AIC', 'AI', 'Air India', 'AIRINDIA', 'India', false, true),
    ('IGO', '6E', 'IndiGo', 'IFLY', 'India', false, true),
    ('AXB', 'IX', 'Air India Express', 'EXPRESS INDIA', 'India', false, true),
    ('SEJ', 'SG', 'SpiceJet', 'SPICEJET', 'India', false, true),
    ('QTR', 'QR', 'Qatar Airways', 'QATARI', 'Qatar', false, true),
    ('UAE', 'EK', 'Emirates', 'EMIRATES', 'UAE', false, true),
    ('FDB', 'FZ', 'flydubai', 'SKYDUBAI', 'UAE', false, true)
ON CONFLICT (icao_code) DO UPDATE 
SET 
    name = EXCLUDED.name,
    callsign = EXCLUDED.callsign,
    is_domestic = EXCLUDED.is_domestic,
    is_active = EXCLUDED.is_active;

-- ------------------------------------------------------------------------------
-- 5. ROW LEVEL SECURITY (RLS) POLICIES
-- Enables safe read access for frontend (anon role) and full admin for backend.
-- ------------------------------------------------------------------------------
ALTER TABLE public.airports ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.runways ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.aircraft_specifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.airlines ENABLE ROW LEVEL SECURITY;

-- Public read policies (anon & authenticated can SELECT)
CREATE POLICY "Allow public read on airports"
    ON public.airports FOR SELECT
    USING (true);

CREATE POLICY "Allow public read on runways"
    ON public.runways FOR SELECT
    USING (true);

CREATE POLICY "Allow public read on aircraft_specifications"
    ON public.aircraft_specifications FOR SELECT
    USING (true);

CREATE POLICY "Allow public read on airlines"
    ON public.airlines FOR SELECT
    USING (true);
