-- ==============================================================================
-- NEPAL AIRSPACE MONITOR - COMPLETE SUPABASE SQL SCRIPT
-- Copy and paste this entire script directly into the Supabase SQL Editor
-- ==============================================================================

-- ------------------------------------------------------------------------------
-- 1. CREATE NEPAL AIRCRAFT TABLE
-- ------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.nepal_aircraft (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    icao24 VARCHAR(10) UNIQUE NOT NULL,                       -- 24-bit Mode-S transponder hex address (e.g. '70a00d')
    registration VARCHAR(20),                                 -- Nepalese tail registration mark (e.g. '9N-AIH', 'NA-058')
    typecode VARCHAR(10),                                     -- ICAO aircraft type designator (e.g. 'AT75', 'DH8D', 'A320', 'AS50')
    model TEXT,                                               -- Manufacturer/commercial model name (e.g. 'ATR 72-500', 'Dash 8-400')
    manufacturer_name TEXT,                                   -- Manufacturer name (e.g. 'Avions De Transport Regional', 'British Aerospace')
    manufacturer_icao TEXT,                                   -- Manufacturer ICAO identifier (e.g. 'ATR', 'AIRBUS', 'BOEING')
    operator TEXT,                                            -- Operating airline/company (e.g. 'Buddha Air', 'Yeti Airlines')
    operator_callsign TEXT,                                   -- Carrier telephony callsign (e.g. 'BUDDHA AIR', 'YETI AIRLINES')
    operator_icao VARCHAR(10),                                -- 3-letter ICAO carrier code (e.g. 'BHA', 'NYT', 'RNA')
    operator_iata VARCHAR(10),                                -- 2-letter IATA carrier code (e.g. 'U4', 'YT', 'RA')
    owner TEXT,                                               -- Legal owner/lessor
    serial_number VARCHAR(50),                                -- Manufacturer Serial Number (MSN)
    icao_aircraft_class VARCHAR(10),                          -- ICAO aircraft class (e.g. 'L2T', 'L2J', 'H1T', 'H2T')
    category_description TEXT,                                -- Emitter / weight category description
    country VARCHAR(50) DEFAULT 'Nepal',                      -- Country of registration
    engines TEXT,                                             -- Installed powerplant description (e.g. 'PWC PW127F')
    built_year VARCHAR(20),                                   -- Year or date built
    first_flight_date DATE,                                   -- Date of maiden flight
    first_seen TIMESTAMPTZ,                                   -- First detected timestamp
    recorded_timestamp TIMESTAMPTZ,                           -- Snapshot timestamp
    registered_date DATE,                                     -- Date registered with Civil Aviation Authority of Nepal (CAAN)
    reg_until DATE,                                           -- Registration certificate expiry date
    status VARCHAR(50),                                       -- Operational / airworthiness status
    modes BOOLEAN DEFAULT FALSE,                              -- Mode-S transponder operational
    adsb BOOLEAN DEFAULT FALSE,                               -- ADS-B Out operational
    acars BOOLEAN DEFAULT FALSE,                              -- ACARS operational
    vdl BOOLEAN DEFAULT FALSE,                                -- VDL Mode 2 operational
    notes TEXT,                                               -- Additional operational notes or remarks
    sel_cal VARCHAR(20),                                      -- Selective Calling (SELCAL) code
    line_number VARCHAR(50),                                  -- Assembly line sequence number
    prev_reg VARCHAR(50),                                     -- Previous foreign registration mark
    next_reg VARCHAR(50),                                     -- Subsequent registration mark if exported
    created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc', NOW()) NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT TIMEZONE('utc', NOW()) NOT NULL
);

-- Indexes for nepal_aircraft
CREATE INDEX IF NOT EXISTS idx_nepal_aircraft_icao24 ON public.nepal_aircraft (icao24);
CREATE INDEX IF NOT EXISTS idx_nepal_aircraft_reg ON public.nepal_aircraft (registration);
CREATE INDEX IF NOT EXISTS idx_nepal_aircraft_typecode ON public.nepal_aircraft (typecode);
CREATE INDEX IF NOT EXISTS idx_nepal_aircraft_operator ON public.nepal_aircraft (operator);
CREATE INDEX IF NOT EXISTS idx_nepal_aircraft_operator_icao ON public.nepal_aircraft (operator_icao);

-- ------------------------------------------------------------------------------
-- 2. SEED MISSING NEPAL STOL & HELICOPTER SPECIFICATIONS
-- ------------------------------------------------------------------------------
INSERT INTO public.aircraft_specifications (
    model, icao_type, category, engine_type, engine_model, powerplant,
    number_of_engines, n_engine, passenger_capacity,
    oew_kg, owe, mtow_kg, mtow, mlw_kg, mlw, fuel_capacity_liters, max_fuel,
    cruise_speed_kts, max_speed_kts, cruise_altitude, nominal_range_nm,
    approach_speed_kts, takeoff_field_length_m, landing_field_length_m,
    fuselage_width, wing_span, wing_area, wing_position, total_length, total_height,
    thruster_type, energy_type, engine_position, max_power
)
SELECT * FROM (VALUES
    ('DHC-6-400 Twin Otter', 'DHC6', 'commuter', 'turboprop', 'PT6A-34', 'Pratt & Whitney Canada PT6A-34', 2, 2, 19, 3121.0, 3121.0, 5670.0, 5670.0, 5579.0, 5579.0, 1446.0, 1150.0, 150, 182, 25000.0, 775, 75, 366, 320, 1.750, 19.810, 39.020, 'high', 15.770, 5.940, 'propeller', 'kerosene', 'wing', 559.0),
    ('Let L-410 Turbolet', 'L410', 'commuter', 'turboprop', 'GE H80-200', 'General Electric H80-200', 2, 2, 19, 4050.0, 4050.0, 6600.0, 6600.0, 6400.0, 6400.0, 1625.0, 1300.0, 200, 224, 20000.0, 810, 82, 500, 480, 1.920, 19.980, 35.180, 'high', 14.490, 5.830, 'propeller', 'kerosene', 'wing', 597.0),
    ('Airbus Helicopters H125 / AS350 B3', 'AS50', 'helicopter', 'turboshaft', 'Safran Arriel 2D', 'Safran Arriel 2D', 1, 1, 6, 1318.0, 1318.0, 2250.0, 2250.0, 2250.0, 2250.0, 540.0, 426.0, 133, 155, 23000.0, 340, 60, 0, 0, 1.870, 10.690, 89.700, 'high', 12.940, 3.340, 'rotor', 'kerosene', 'fuselage', 632.0),
    ('Bell 407GXP', 'B407', 'helicopter', 'turboshaft', 'Rolls-Royce 250-C47B/8', 'Rolls-Royce 250-C47B/8', 1, 1, 6, 1221.0, 1221.0, 2381.0, 2381.0, 2381.0, 2381.0, 492.0, 388.0, 133, 140, 18000.0, 324, 60, 0, 0, 1.500, 10.670, 89.400, 'high', 12.700, 3.560, 'rotor', 'kerosene', 'fuselage', 606.0),
    ('Bell 505 Jet Ranger X', 'B505', 'helicopter', 'turboshaft', 'Safran Arrius 2R', 'Safran Arrius 2R', 1, 1, 4, 991.0, 991.0, 1669.0, 1669.0, 1669.0, 1669.0, 322.0, 254.0, 125, 135, 18610.0, 333, 55, 0, 0, 1.400, 11.280, 99.900, 'high', 12.930, 3.250, 'rotor', 'kerosene', 'fuselage', 377.0),
    ('Leonardo AW139', 'A139', 'helicopter', 'turboshaft', 'PT6C-67C', 'Pratt & Whitney Canada PT6C-67C', 2, 2, 15, 3622.0, 3622.0, 6400.0, 6400.0, 6400.0, 6400.0, 2088.0, 1645.0, 165, 167, 20000.0, 573, 65, 0, 0, 2.260, 13.800, 149.570, 'high', 16.660, 4.980, 'rotor', 'kerosene', 'fuselage', 1142.0)
) AS v(
    model, icao_type, category, engine_type, engine_model, powerplant,
    number_of_engines, n_engine, passenger_capacity,
    oew_kg, owe, mtow_kg, mtow, mlw_kg, mlw, fuel_capacity_liters, max_fuel,
    cruise_speed_kts, max_speed_kts, cruise_altitude, nominal_range_nm,
    approach_speed_kts, takeoff_field_length_m, landing_field_length_m,
    fuselage_width, wing_span, wing_area, wing_position, total_length, total_height,
    thruster_type, energy_type, engine_position, max_power
)
WHERE NOT EXISTS (
    SELECT 1 FROM public.aircraft_specifications s 
    WHERE s.icao_type = v.icao_type OR s.model = v.model
);

-- ------------------------------------------------------------------------------
-- 3. POPULATE NEPAL AIRCRAFT DATASET (82 RECORDS)
-- ------------------------------------------------------------------------------
INSERT INTO public.nepal_aircraft (
    icao24, registration, typecode, model, manufacturer_name, manufacturer_icao,
    operator, operator_callsign, operator_icao, operator_iata, owner, serial_number,
    icao_aircraft_class, category_description, country, engines, built_year,
    first_flight_date, first_seen, recorded_timestamp, registered_date, reg_until,
    status, modes, adsb, acars, vdl, notes, sel_cal, line_number, prev_reg, next_reg
) VALUES
('70a00d', '9N-AIH', 'JS41', 'Jetstream 41 -01', 'British Aerospace', 'JETSTREAM', 'Yeti Airlines', 'YETI AIRLINES', 'NYT', NULL, 'Yeti Airlines', '41085', 'L2T', NULL, 'Nepal', NULL, NULL, NULL, NULL, '2019-02-12 17:07:06', NULL, NULL, NULL, FALSE, FALSE, FALSE, FALSE, NULL, NULL, NULL, NULL, NULL),
('70a04c', 'NA-058', 'A139', NULL, NULL, 'LEONARDO', NULL, NULL, NULL, NULL, NULL, NULL, 'H2T', NULL, 'Nepal', NULL, NULL, NULL, NULL, '1970-01-01 01:00:00', NULL, NULL, NULL, FALSE, FALSE, FALSE, FALSE, NULL, NULL, NULL, NULL, NULL),
('70a062', '9N-ACB', 'B752', '757 2F8C', 'Boeing', 'BOEING', 'Nepal Airlines', 'ROYAL NEPAL', 'RNA', 'RA', 'Nepal Airlines', '23863', 'L2J', NULL, 'Nepal', NULL, NULL, NULL, NULL, '2019-02-24 16:42:59', NULL, NULL, NULL, FALSE, FALSE, FALSE, FALSE, NULL, NULL, NULL, NULL, NULL),
('70a7b7', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Nepal', NULL, NULL, NULL, NULL, '1970-01-01 01:00:00', NULL, NULL, NULL, FALSE, FALSE, FALSE, FALSE, NULL, NULL, NULL, NULL, NULL),
('70a8e5', '9N-AOH', 'AT75', 'ATR 72-500', NULL, NULL, 'Yeti Airlines', NULL, 'NYT', 'YT', NULL, NULL, NULL, NULL, 'Nepal', NULL, NULL, NULL, NULL, '2024-06-25 12:27:44', NULL, NULL, NULL, FALSE, FALSE, FALSE, FALSE, NULL, NULL, NULL, NULL, NULL),
('70a8e7', '9N-AOM', 'DH8D', 'De Havilland Canada Dash 8-400', NULL, NULL, 'Shree Airlines', NULL, 'SHA', 'N9', NULL, NULL, NULL, NULL, 'Nepal', NULL, NULL, NULL, NULL, '2024-06-25 12:35:50', NULL, NULL, NULL, FALSE, FALSE, FALSE, FALSE, NULL, NULL, NULL, NULL, NULL),
('70a8e9', '9N-AOL', 'DH8D', 'De Havilland Canada Dash 8-400', NULL, NULL, 'Shree Airlines', NULL, 'SHA', 'N9', NULL, NULL, NULL, NULL, 'Nepal', NULL, NULL, NULL, NULL, '2024-06-25 12:27:44', NULL, NULL, NULL, FALSE, FALSE, FALSE, FALSE, NULL, NULL, NULL, NULL, NULL),
('70a8eb', '9N-AOG', 'AT75', 'ATR 72-500', NULL, NULL, 'Buddha Air', NULL, 'BHA', 'U4', NULL, NULL, NULL, NULL, 'Nepal', NULL, NULL, NULL, NULL, '2025-06-26 16:26:28', NULL, NULL, NULL, FALSE, FALSE, FALSE, FALSE, NULL, NULL, NULL, NULL, NULL),
('70a8ee', '9N-AOC', 'AT75', 'ATR 72-500', NULL, NULL, 'Buddha Air', NULL, 'BHA', 'U4', NULL, NULL, NULL, NULL, 'Nepal', NULL, NULL, NULL, NULL, '2024-06-25 12:27:44', NULL, NULL, NULL, FALSE, FALSE, FALSE, FALSE, NULL, NULL, NULL, NULL, NULL),
('70a8f0', '9N-AOE', 'AS50', 'Airbus Helicopters H125', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Nepal', NULL, NULL, NULL, NULL, '2024-06-25 12:42:30', NULL, NULL, NULL, FALSE, FALSE, FALSE, FALSE, NULL, NULL, NULL, NULL, NULL),
('70a8f2', '9N-AOD', 'AS50', 'Airbus Helicopters H125', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Nepal', NULL, NULL, NULL, NULL, '2025-06-26 16:41:04', NULL, NULL, NULL, FALSE, FALSE, FALSE, FALSE, NULL, NULL, NULL, NULL, NULL),
('70a8f6', '9N-AOF', 'AT75', 'ATR 72-500', NULL, NULL, 'Yeti Airlines', NULL, 'NYT', 'YT', NULL, NULL, NULL, NULL, 'Nepal', NULL, NULL, NULL, NULL, '2024-06-25 12:27:44', NULL, NULL, NULL, FALSE, FALSE, FALSE, FALSE, NULL, NULL, NULL, NULL, NULL),
('70a8fe', '9N-AOK', 'DH8D', 'De Havilland Canada Dash 8-400', NULL, NULL, 'Shree Airlines', NULL, 'SHA', 'N9', NULL, NULL, NULL, NULL, 'Nepal', NULL, NULL, NULL, NULL, '2024-06-25 12:27:44', NULL, NULL, NULL, FALSE, FALSE, FALSE, FALSE, NULL, NULL, NULL, NULL, NULL),
('70a96a', '9N-AHR', 'D228', 'Dornier 228-202', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Nepal', NULL, NULL, NULL, NULL, '2024-06-25 12:42:30', NULL, NULL, NULL, FALSE, FALSE, FALSE, FALSE, NULL, NULL, NULL, NULL, NULL),
('70a96f', '9N-AHV', 'JS41', 'BAe Jetstream 41', 'British Aerospace', 'JETSTREAM', 'Yeti Airlines', 'YETI AIRLINES', 'NYT', NULL, 'Yeti Airlines', '41077', 'L2T', NULL, 'Nepal', NULL, NULL, NULL, NULL, '2019-02-12 17:09:52', NULL, NULL, NULL, FALSE, FALSE, FALSE, FALSE, NULL, NULL, NULL, NULL, NULL),
('70a975', '9N-AHY', 'JS41', 'BAe Jetstream 41', 'British Aerospace', 'JETSTREAM', 'Yeti Airlines', 'YETI AIRLINES', 'NYT', NULL, 'Yeti Airlines', '41066', 'L2T', NULL, 'Nepal', NULL, NULL, NULL, NULL, '2019-02-12 17:08:22', NULL, NULL, NULL, FALSE, FALSE, FALSE, FALSE, NULL, NULL, NULL, NULL, NULL),
('70a979', '9N-AHW', 'JS41', 'Jetstream 41 -01', 'British Aerospace', 'JETSTREAM', 'Yeti Airlines', 'YETI AIRLINES', 'NYT', NULL, 'Yeti Airlines', '41078', 'L2T', NULL, 'Nepal', NULL, NULL, NULL, NULL, '2019-02-12 17:08:46', NULL, NULL, NULL, FALSE, FALSE, FALSE, FALSE, NULL, NULL, NULL, NULL, NULL),
('70a97c', '9N-AHU', 'JS41', 'Jetstream 41 -01', 'British Aerospace', 'JETSTREAM', 'Yeti Airlines', 'YETI AIRLINES', 'NYT', NULL, 'Yeti Airlines', '41072', 'L2T', NULL, 'Nepal', NULL, NULL, NULL, NULL, '2019-02-12 17:09:02', NULL, NULL, NULL, FALSE, FALSE, FALSE, FALSE, NULL, NULL, NULL, NULL, NULL),
('70a9a1', '9N-ANT', 'AS50', 'Airbus Helicopters H125', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Nepal', NULL, NULL, NULL, NULL, '2025-06-26 16:37:54', NULL, NULL, NULL, FALSE, FALSE, FALSE, FALSE, NULL, NULL, NULL, NULL, NULL),
('70a9a5', '9N-ANH', 'AT75', NULL, NULL, 'ATR', NULL, NULL, NULL, NULL, NULL, NULL, 'L2T', NULL, 'Nepal', NULL, NULL, NULL, NULL, '1970-01-01 01:00:00', NULL, NULL, NULL, FALSE, FALSE, FALSE, FALSE, NULL, NULL, NULL, NULL, NULL),
('70a9a7', '9N-ANM', 'CRJ2', 'Mitsubishi CRJ-200', NULL, NULL, 'Saurya Airlines', NULL, 'SAU', NULL, NULL, NULL, NULL, NULL, 'Nepal', NULL, NULL, NULL, NULL, '2024-06-25 12:35:50', NULL, NULL, NULL, FALSE, FALSE, FALSE, FALSE, NULL, NULL, NULL, NULL, NULL),
('70a9a9', '9N-ANL', 'AS50', 'Airbus Helicopters H125', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Nepal', NULL, NULL, NULL, NULL, '2024-06-25 12:42:30', NULL, NULL, NULL, FALSE, FALSE, FALSE, FALSE, NULL, NULL, NULL, NULL, NULL),
('70a9aa', '9N-ANR', 'DH8D', 'De Havilland Canada Dash 8-400', NULL, NULL, 'Shree Airlines', NULL, 'SHA', 'N9', NULL, NULL, NULL, NULL, 'Nepal', NULL, NULL, NULL, NULL, '2024-06-25 12:27:44', NULL, NULL, NULL, FALSE, FALSE, FALSE, FALSE, NULL, NULL, NULL, NULL, NULL),
('70a9ab', '9N-ANG', 'AT75', 'ATR 72-500', NULL, NULL, 'Yeti Airlines', NULL, 'NYT', 'YT', NULL, NULL, NULL, NULL, 'Nepal', NULL, NULL, NULL, NULL, '2024-06-25 12:27:44', NULL, NULL, NULL, FALSE, FALSE, FALSE, FALSE, NULL, NULL, NULL, NULL, NULL),
('70a9ac', '9N-ANI', 'AT75', NULL, NULL, 'ATR', NULL, NULL, NULL, NULL, NULL, NULL, 'L2T', NULL, 'Nepal', NULL, NULL, NULL, NULL, '1970-01-01 01:00:00', NULL, NULL, NULL, FALSE, FALSE, FALSE, FALSE, NULL, NULL, NULL, NULL, NULL),
('70a9ad', '9N-ANP', 'AT75', NULL, NULL, 'ATR', NULL, NULL, NULL, NULL, NULL, NULL, 'L2T', NULL, 'Nepal', NULL, NULL, NULL, NULL, '1970-01-01 01:00:00', NULL, NULL, NULL, FALSE, FALSE, FALSE, FALSE, NULL, NULL, NULL, NULL, NULL),
('70a9ae', '9N-ANC', 'AT75', '72-212A', NULL, 'ATR', 'Yeti Airlines', 'YETI AIRLINES', 'NYT', NULL, NULL, '754', 'L2T', NULL, 'Nepal', 'PWC PW127F', NULL, '2001-08-20', NULL, '2023-01-20 15:39:22', NULL, NULL, NULL, FALSE, FALSE, FALSE, FALSE, NULL, NULL, NULL, NULL, NULL),
('70a9b0', '9N-ANE', 'DH8D', NULL, NULL, 'DE HAVILLAND CANADA', NULL, NULL, NULL, NULL, NULL, NULL, 'L2T', NULL, 'Nepal', NULL, NULL, NULL, NULL, '1970-01-01 01:00:00', NULL, NULL, NULL, FALSE, FALSE, FALSE, FALSE, NULL, NULL, NULL, NULL, NULL),
('70a9b1', '9N-ANZ', 'AT75', 'ATR 72-500', NULL, NULL, 'Buddha Air', NULL, 'BHA', 'U4', NULL, NULL, NULL, NULL, 'Nepal', NULL, NULL, NULL, NULL, '2025-06-26 16:26:28', NULL, NULL, NULL, FALSE, FALSE, FALSE, FALSE, NULL, NULL, NULL, NULL, NULL),
('70a9b2', '9N-AND', 'L410', NULL, NULL, 'LET', NULL, NULL, NULL, NULL, NULL, NULL, 'L2T', NULL, 'Nepal', NULL, NULL, NULL, NULL, '1970-01-01 01:00:00', NULL, NULL, NULL, FALSE, FALSE, FALSE, FALSE, NULL, NULL, NULL, NULL, NULL),
('70a9b4', '9N-ANS', 'DH8D', NULL, NULL, 'DE HAVILLAND CANADA', NULL, NULL, NULL, NULL, NULL, NULL, 'L2T', NULL, 'Nepal', NULL, NULL, NULL, NULL, '1970-01-01 01:00:00', NULL, NULL, NULL, FALSE, FALSE, FALSE, FALSE, NULL, NULL, NULL, NULL, NULL),
('70a9b6', '9N-ANF', 'DH8D', 'De Havilland Canada Dash 8-400', NULL, NULL, 'Shree Airlines', NULL, 'SHA', 'N9', NULL, NULL, NULL, NULL, 'Nepal', NULL, NULL, NULL, NULL, '2024-06-25 12:27:44', NULL, NULL, NULL, FALSE, FALSE, FALSE, FALSE, NULL, NULL, NULL, NULL, NULL),
('70a9b7', '9N-ANX', 'B505', 'Bell 505 Jet Ranger X', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Nepal', NULL, NULL, NULL, NULL, '2024-06-25 12:27:44', NULL, NULL, NULL, FALSE, FALSE, FALSE, FALSE, NULL, NULL, NULL, NULL, NULL),
('70a9b9', '9N-ANW', 'AT75', 'ATR 72-500', NULL, NULL, 'Buddha Air', NULL, 'BHA', 'U4', NULL, NULL, NULL, NULL, 'Nepal', NULL, NULL, NULL, NULL, '2024-06-25 12:35:50', NULL, NULL, NULL, FALSE, FALSE, FALSE, FALSE, NULL, NULL, NULL, NULL, NULL),
('70a9bd', '9N-ANQ', 'AT75', 'ATR 72-500', NULL, NULL, 'Buddha Air', NULL, 'BHA', 'U4', NULL, NULL, NULL, NULL, 'Nepal', NULL, NULL, NULL, NULL, '2024-06-25 12:35:50', NULL, NULL, NULL, FALSE, FALSE, FALSE, FALSE, NULL, NULL, NULL, NULL, NULL),
('70a9e6', '9N-AMN', 'AT75', 'ATR 72 500', 'Avions De Transport Regional', 'ATR', 'Yeti Airlines', 'YETI AIRLINES', 'NYT', NULL, 'Yeti Airlines', '876', 'L2T', NULL, 'Nepal', NULL, NULL, NULL, NULL, '2019-02-24 16:45:09', NULL, NULL, NULL, FALSE, FALSE, FALSE, FALSE, NULL, NULL, NULL, NULL, NULL),
('70a9e7', '9N-AMM', 'AT75', 'ATR 72-500', 'Avions De Transport Regional', 'ATR', 'Yeti Airlines', 'YETI AIRLINES', 'NYT', NULL, 'Yeti Airlines', '749', 'L2T', NULL, 'Nepal', NULL, NULL, NULL, NULL, '2019-02-12 17:14:55', NULL, NULL, NULL, FALSE, FALSE, FALSE, FALSE, NULL, NULL, NULL, NULL, NULL),
('70a9e9', '9N-AML', 'AS50', 'Airbus Helicopters H125', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Nepal', NULL, NULL, NULL, NULL, '2024-06-25 12:35:50', NULL, NULL, NULL, FALSE, FALSE, FALSE, FALSE, NULL, NULL, NULL, NULL, NULL),
('70a9eb', '9N-AMG', 'L410', 'Let L-410 Turbolet', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Nepal', NULL, NULL, NULL, NULL, '2024-06-25 12:35:50', NULL, NULL, NULL, FALSE, FALSE, FALSE, FALSE, NULL, NULL, NULL, NULL, NULL),
('70a9ee', '9N-AMC', 'CRJ2', 'Mitsubishi CRJ-200ER', NULL, NULL, 'Shree Airlines', NULL, 'SHA', 'N9', NULL, NULL, NULL, NULL, 'Nepal', NULL, NULL, NULL, NULL, '2024-06-25 12:27:44', NULL, NULL, NULL, FALSE, FALSE, FALSE, FALSE, NULL, NULL, NULL, NULL, NULL),
('70a9f0', '9N-AME', 'CRJ2', 'Mitsubishi CRJ-200ER', NULL, NULL, 'Saurya Airlines', NULL, 'SAU', NULL, NULL, NULL, NULL, NULL, 'Nepal', NULL, NULL, NULL, NULL, '2024-06-25 12:27:44', NULL, NULL, NULL, FALSE, FALSE, FALSE, FALSE, NULL, NULL, NULL, NULL, NULL),
('70a9f1', '9N-AMZ', 'AT75', 'ATR 72-500', NULL, NULL, 'Yeti Airlines', NULL, 'NYT', 'YT', NULL, NULL, NULL, NULL, 'Nepal', NULL, NULL, NULL, NULL, '2024-06-25 12:42:30', NULL, NULL, NULL, FALSE, FALSE, FALSE, FALSE, NULL, NULL, NULL, NULL, NULL),
('70a9f2', '9N-AMD', 'AT75', 'ATR 72-500', 'Avions De Transport Regional', 'ATR', 'Buddha Air', 'BUDDHA AIR', 'BHA', NULL, 'Buddha Air', '735', 'L2T', NULL, 'Nepal', NULL, NULL, NULL, NULL, '2019-02-24 16:46:44', NULL, NULL, NULL, FALSE, FALSE, FALSE, FALSE, NULL, NULL, NULL, NULL, NULL),
('70a9f3', '9N-AMB', 'CRJ7', NULL, NULL, 'CANADAIR', NULL, NULL, NULL, NULL, NULL, NULL, 'L2J', NULL, 'Nepal', NULL, NULL, NULL, NULL, '1970-01-01 01:00:00', NULL, NULL, NULL, FALSE, FALSE, FALSE, FALSE, NULL, NULL, NULL, NULL, NULL),
('70a9f4', '9N-AMS', 'AS50', 'Airbus Helicopters H125', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Nepal', NULL, NULL, NULL, NULL, '2025-06-26 16:37:54', NULL, NULL, NULL, FALSE, FALSE, FALSE, FALSE, NULL, NULL, NULL, NULL, NULL),
('70a9f5', '9N-AMY', 'AT75', NULL, NULL, 'ATR', NULL, NULL, NULL, NULL, NULL, NULL, 'L2T', NULL, 'Nepal', NULL, NULL, NULL, NULL, '1970-01-01 01:00:00', NULL, NULL, NULL, FALSE, FALSE, FALSE, FALSE, NULL, NULL, NULL, NULL, NULL),
('70a9f6', '9N-AMF', 'AT75', 'ATR 72-500', 'Avions De Transport Regional', 'ATR', 'Buddha Air', 'BUDDHA AIR', 'BHA', NULL, 'Buddha Air', '764', 'L2T', 'No ADS-B Emitter Category Information', 'Nepal', NULL, NULL, NULL, NULL, '2019-02-24 16:46:14', NULL, NULL, NULL, FALSE, FALSE, FALSE, FALSE, NULL, NULL, NULL, NULL, NULL),
('70a9f8', '9N-AMA', 'CRJ2', 'Mitsubishi CRJ-200ER', NULL, NULL, 'Shree Airlines', NULL, 'SHA', 'N9', NULL, NULL, NULL, NULL, 'Nepal', NULL, NULL, NULL, NULL, '2022-05-08 13:47:53', NULL, NULL, NULL, FALSE, FALSE, FALSE, FALSE, NULL, NULL, NULL, NULL, NULL),
('70a9fc', '9N-AMU', 'AT75', 'ATR 72-500', 'Avions De Transport Regional', 'ATR', 'Buddha Air', 'BUDDHA AIR', 'BHA', NULL, 'Buddha Air', '759', 'L2T', NULL, 'Nepal', NULL, NULL, NULL, NULL, '2019-02-24 16:46:29', NULL, NULL, NULL, FALSE, FALSE, FALSE, FALSE, NULL, NULL, NULL, NULL, NULL),
('70a9fd', '9N-AMQ', 'AS50', 'Airbus Helicopters H125', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Nepal', NULL, NULL, NULL, NULL, '2025-06-26 16:37:54', NULL, NULL, NULL, FALSE, FALSE, FALSE, FALSE, NULL, NULL, NULL, NULL, NULL),
('70aa61', '9N-ALT', 'B407', 'Bell 407GXP', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Nepal', NULL, NULL, NULL, NULL, '2024-06-25 12:27:44', NULL, NULL, NULL, FALSE, FALSE, FALSE, FALSE, NULL, NULL, NULL, NULL, NULL),
('70aa63', '9N-ALO', 'DHC6', NULL, NULL, 'VIKING (2)', NULL, NULL, NULL, NULL, NULL, NULL, 'L2T', NULL, 'Nepal', NULL, NULL, NULL, NULL, '2019-03-03 11:12:00', NULL, NULL, NULL, FALSE, FALSE, FALSE, FALSE, NULL, NULL, NULL, NULL, NULL),
('70aa66', '9N-ALN', 'AT75', 'ATR 72-500', 'Avions De Transport Regional', 'ATR', 'Yeti Airlines', 'YETI AIRLINES', 'NYT', NULL, 'Yeti Airlines', '776', 'L2T', NULL, 'Nepal', NULL, NULL, NULL, NULL, '2019-02-12 17:12:55', NULL, NULL, NULL, FALSE, FALSE, FALSE, FALSE, NULL, NULL, NULL, NULL, NULL),
('70aa67', '9N-ALM', 'A320', 'A320 214SL', 'Airbus', 'AIRBUS', 'Himalaya Airlines', 'HIM', 'HIM', 'H9', 'Himalaya Airlines', '6626', 'L2J', 'No ADS-B Emitter Category Information', 'Nepal', NULL, NULL, NULL, NULL, '2019-02-12 16:54:02', NULL, NULL, NULL, FALSE, FALSE, FALSE, FALSE, NULL, NULL, NULL, NULL, NULL),
('70aa6d', '9N-ALP', 'AS50', 'Squirrel AS.350 B3', 'Airbus Helicopters', 'LOT', NULL, NULL, NULL, NULL, 'Private', '8022', 'H1T', NULL, 'Nepal', NULL, NULL, NULL, NULL, '2017-09-15 00:10:19', NULL, NULL, NULL, FALSE, FALSE, FALSE, FALSE, NULL, NULL, NULL, NULL, NULL),
('70aa6f', '9N-ALV', 'A320', 'A320 214SL', 'Airbus', 'AIRBUS', 'Himalaya Airlines', 'HIM', 'HIM', 'H9', 'Himalaya Airlines', '7503', 'L2J', 'Large (75000 to 300000 lbs)', 'Nepal', NULL, NULL, NULL, NULL, '2019-02-12 16:57:34', NULL, NULL, NULL, FALSE, FALSE, FALSE, FALSE, NULL, NULL, NULL, NULL, NULL),
('70aa71', '9N-ALZ', 'A332', 'Airbus A330-243', 'Airbus', 'AIRBUS', 'Nepal Airlines', 'ROYAL NEPAL', 'RNA', 'RA', 'Nepal Airlines', '1878', 'L2J', NULL, 'Nepal', NULL, NULL, NULL, NULL, '2019-02-24 16:42:09', NULL, NULL, NULL, FALSE, FALSE, FALSE, FALSE, NULL, NULL, NULL, NULL, NULL),
('70aa75', '9N-ALY', 'A332', 'Airbus A330-243', 'Airbus', 'AIRBUS', 'Nepal Airlines', 'ROYAL NEPAL', 'RNA', 'RA', 'Nepal Airlines', '1872', 'L2J', NULL, 'Nepal', NULL, NULL, NULL, NULL, '2019-02-24 16:43:25', NULL, NULL, NULL, FALSE, FALSE, FALSE, FALSE, NULL, NULL, NULL, NULL, NULL),
('70aa79', '9N-ALW', 'A320', 'A320 214SL', 'Airbus', 'AIRBUS', 'Himalaya Airlines', 'HIM', 'HIM', 'H9', 'Himalaya Airlines', '7604', 'L2J', 'Large (75000 to 300000 lbs)', 'Nepal', NULL, NULL, NULL, NULL, '2019-02-12 16:58:38', NULL, NULL, NULL, FALSE, FALSE, FALSE, FALSE, NULL, NULL, NULL, NULL, NULL),
('70ab21', '9N-AIT', 'AT43', 'ATR 42-320', 'Avions De Transport Regional', 'ATR', 'Buddha Air', 'BUDDHA AIR', 'BHA', NULL, 'Buddha Air', '409', 'L2T', NULL, 'Nepal', NULL, NULL, NULL, NULL, '2019-02-12 16:36:04', NULL, NULL, NULL, FALSE, FALSE, FALSE, FALSE, NULL, NULL, NULL, NULL, NULL),
('70ab26', '9N-AIN', 'AT43', 'ATR 42-320', 'Avions De Transport Regional', 'ATR', 'Buddha Air', 'BUDDHA AIR', 'BHA', NULL, 'Buddha Air', '403', 'L2T', NULL, 'Nepal', NULL, NULL, NULL, NULL, '2019-02-12 16:33:52', NULL, NULL, NULL, FALSE, FALSE, FALSE, FALSE, NULL, NULL, NULL, NULL, NULL),
('70ab27', '9N-AIM', 'AT43', 'ATR 42-320', 'Atr', 'ATR', 'Buddha Air', 'BUDDHA AIR', 'BHA', NULL, 'Buddha Air', '388', 'L2T', NULL, 'Nepal', NULL, NULL, NULL, NULL, '2019-02-12 16:28:33', NULL, NULL, NULL, FALSE, FALSE, FALSE, FALSE, NULL, NULL, NULL, NULL, NULL),
('70ab30', '9N-AIE', 'D228', 'Dornier 228-202K', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Nepal', NULL, NULL, NULL, NULL, '2024-06-25 12:42:30', NULL, NULL, NULL, FALSE, FALSE, FALSE, FALSE, NULL, NULL, NULL, NULL, NULL),
('70ac21', '9N-AET', 'DHC6', NULL, NULL, 'VIKING (2)', NULL, NULL, NULL, NULL, NULL, NULL, 'L2T', NULL, 'Nepal', NULL, NULL, NULL, NULL, '1970-01-01 01:00:00', NULL, NULL, NULL, FALSE, FALSE, FALSE, FALSE, NULL, NULL, NULL, NULL, NULL),
('70ac2f', '9N-AEV', 'DHC6', NULL, NULL, 'VIKING (2)', NULL, NULL, NULL, NULL, NULL, NULL, 'L2T', NULL, 'Nepal', NULL, NULL, NULL, NULL, '1970-01-01 01:00:00', NULL, NULL, NULL, FALSE, FALSE, FALSE, FALSE, NULL, NULL, NULL, NULL, NULL),
('70ac30', '9N-AEE', 'B190', 'Beechcraft 1900D', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Nepal', NULL, NULL, NULL, NULL, '2024-06-25 12:27:44', NULL, NULL, NULL, FALSE, FALSE, FALSE, FALSE, NULL, NULL, NULL, NULL, NULL),
('70ac39', '9N-AEW', 'B190', 'Beechcraft 1900D', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Nepal', NULL, NULL, NULL, NULL, '2024-06-25 12:35:50', NULL, NULL, NULL, FALSE, FALSE, FALSE, FALSE, NULL, NULL, NULL, NULL, NULL),
('70aca9', '9N-AJL', 'AT75', 'ATR 72-500', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Nepal', NULL, NULL, NULL, NULL, '2024-06-25 12:42:30', NULL, NULL, NULL, FALSE, FALSE, FALSE, FALSE, NULL, NULL, NULL, NULL, NULL),
('70ae27', '9N-RAM', 'A139', NULL, NULL, 'LEONARDO', NULL, NULL, NULL, NULL, NULL, NULL, 'H2T', NULL, 'Nepal', NULL, NULL, NULL, NULL, '1970-01-01 01:00:00', NULL, NULL, NULL, FALSE, FALSE, FALSE, FALSE, NULL, NULL, NULL, NULL, NULL),
('70aea3', '9N-AJO', 'AT75', 'ATR 72-500', 'Avions De Transport Regional', 'ATR', 'Buddha Air', 'BUDDHA AIR', 'BHA', NULL, 'Buddha Air', '535', 'L2T', NULL, 'Nepal', NULL, NULL, NULL, NULL, '2019-02-12 16:38:18', NULL, NULL, NULL, FALSE, FALSE, FALSE, FALSE, NULL, NULL, NULL, NULL, NULL),
('70aea5', '9N-AJH', 'D28D', 'Dornier Do 228-212', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Nepal', NULL, NULL, NULL, NULL, '2024-06-25 12:35:50', NULL, NULL, NULL, FALSE, FALSE, FALSE, FALSE, NULL, NULL, NULL, NULL, NULL),
('70aea9', '9N-AJL', 'AT75', NULL, NULL, 'ATR', NULL, NULL, NULL, NULL, NULL, NULL, 'L2T', NULL, 'Nepal', NULL, NULL, NULL, NULL, '1970-01-01 01:00:00', NULL, NULL, NULL, FALSE, FALSE, FALSE, FALSE, NULL, NULL, NULL, NULL, NULL),
('70aeae', '9N-AJC', 'JS41', 'BAe Jetstream 41', 'British Aerospace', 'JETSTREAM', 'Yeti Airlines', 'YETI AIRLINES', 'NYT', NULL, 'Yeti Airlines', '41096', 'L2T', NULL, 'Nepal', NULL, NULL, NULL, NULL, '2019-02-12 17:09:24', NULL, NULL, NULL, FALSE, FALSE, FALSE, FALSE, NULL, NULL, NULL, NULL, NULL),
('70aeb4', '9N-AJS', 'AT75', 'ATR 72 500', 'Avions De Transport Regional', 'ATR', 'Buddha Air', 'BUDDHA AIR', 'BHA', NULL, 'Buddha Air', '531', 'L2T', NULL, 'Nepal', NULL, NULL, NULL, NULL, '2019-02-24 16:47:26', NULL, NULL, NULL, FALSE, FALSE, FALSE, FALSE, NULL, NULL, NULL, NULL, NULL),
('70aeb7', '9N-AJX', 'AT75', 'ATR 72-500', 'Avions De Transport Regional', 'ATR', 'Buddha Air', 'BUDDHA AIR', 'BHA', NULL, 'Buddha Air', '578', 'L2T', NULL, 'Nepal', NULL, NULL, NULL, NULL, '2019-02-24 16:47:40', NULL, NULL, NULL, FALSE, FALSE, FALSE, FALSE, NULL, NULL, NULL, NULL, NULL),
('70aebe', '9N-AJK', 'A319', NULL, NULL, 'AIRBUS', NULL, NULL, NULL, NULL, NULL, NULL, 'L2J', NULL, 'Nepal', NULL, NULL, NULL, NULL, '1970-01-01 01:00:00', NULL, NULL, NULL, FALSE, FALSE, FALSE, FALSE, NULL, NULL, NULL, NULL, NULL),
('70af73', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Nepal', NULL, NULL, NULL, NULL, '1970-01-01 01:00:00', NULL, NULL, NULL, FALSE, FALSE, FALSE, FALSE, NULL, NULL, NULL, NULL, NULL),
('70afa9', '9N-AKL', 'DHC6', 'Viking DHC-6-400 Twin Otter', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Nepal', NULL, NULL, NULL, NULL, '2024-06-25 12:35:50', NULL, NULL, NULL, FALSE, FALSE, FALSE, FALSE, NULL, NULL, NULL, NULL, NULL),
('70afb0', '9N-XXA', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Nepal', NULL, NULL, NULL, NULL, '2025-06-26 16:41:04', NULL, NULL, NULL, FALSE, FALSE, FALSE, FALSE, NULL, NULL, NULL, NULL, NULL),
('70afb1', '9N-AKZ', 'L410', 'Let L-410 Turbolet', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Nepal', NULL, NULL, NULL, NULL, '2025-06-26 16:37:54', NULL, NULL, NULL, FALSE, FALSE, FALSE, FALSE, NULL, NULL, NULL, NULL, NULL),
('70afb7', '9N-AKX', 'A320', 'A320 233SL', 'Airbus', 'AIRBUS', 'Nepal Airlines', 'ROYAL NEPAL', 'RNA', 'RA', 'Nepal Airlines', '6555', 'L2J', 'Large (75000 to 300000 lbs)', 'Nepal', NULL, NULL, NULL, NULL, '2019-02-24 16:43:59', NULL, NULL, NULL, FALSE, FALSE, FALSE, FALSE, NULL, NULL, NULL, NULL, NULL),
('70afb9', '9N-AKW', 'A320', 'A320 233SL', 'Airbus', 'AIRBUS', 'Nepal Airlines', 'ROYAL NEPAL', 'RNA', 'RA', 'Nepal Airlines', '6445', 'L2J', 'Large (75000 to 300000 lbs)', 'Nepal', NULL, NULL, NULL, NULL, '2019-02-24 16:44:09', NULL, NULL, NULL, FALSE, FALSE, FALSE, FALSE, NULL, NULL, NULL, NULL, NULL)
ON CONFLICT (icao24) DO UPDATE SET
    registration = EXCLUDED.registration,
    typecode = EXCLUDED.typecode,
    model = EXCLUDED.model,
    operator = EXCLUDED.operator,
    operator_callsign = EXCLUDED.operator_callsign,
    operator_icao = EXCLUDED.operator_icao,
    operator_iata = EXCLUDED.operator_iata,
    owner = EXCLUDED.owner,
    serial_number = EXCLUDED.serial_number,
    status = EXCLUDED.status,
    modes = EXCLUDED.modes,
    adsb = EXCLUDED.adsb,
    acars = EXCLUDED.acars,
    vdl = EXCLUDED.vdl,
    updated_at = TIMEZONE('utc', NOW());

-- ------------------------------------------------------------------------------
-- 4. CREATE JUNCTION TABLE: nepal_aircraft_specifications
-- ------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.nepal_aircraft_specifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nepal_aircraft_id BIGINT NOT NULL REFERENCES public.nepal_aircraft(id) ON DELETE CASCADE,
    specification_id BIGINT NOT NULL REFERENCES public.aircraft_specifications(id) ON DELETE CASCADE,
    match_method VARCHAR(50) DEFAULT 'typecode_match' NOT NULL, -- 'exact_typecode', 'model_variant', 'iata_mapping'
    match_confidence NUMERIC(3, 2) DEFAULT 1.00 NOT NULL,       -- Confidence score (0.00 - 1.00)
    is_primary BOOLEAN DEFAULT TRUE NOT NULL,                   -- Primary specification baseline
    notes TEXT,                                                 -- Detailed mapping / variant notes
    created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc', NOW()) NOT NULL,
    CONSTRAINT uq_nepal_aircraft_specification UNIQUE (nepal_aircraft_id, specification_id)
);

-- Indexes for junction lookups
CREATE INDEX IF NOT EXISTS idx_nas_nepal_aircraft_id ON public.nepal_aircraft_specifications (nepal_aircraft_id);
CREATE INDEX IF NOT EXISTS idx_nas_specification_id ON public.nepal_aircraft_specifications (specification_id);
CREATE INDEX IF NOT EXISTS idx_nas_composite ON public.nepal_aircraft_specifications (nepal_aircraft_id, specification_id);

-- ------------------------------------------------------------------------------
-- 5. AUTOMATICALLY POPULATE JUNCTION TABLE LINKS
-- ------------------------------------------------------------------------------
INSERT INTO public.nepal_aircraft_specifications (
    nepal_aircraft_id, specification_id, match_method, match_confidence, is_primary, notes
)
SELECT 
    na.id AS nepal_aircraft_id,
    s.id AS specification_id,
    CASE 
        WHEN UPPER(s.icao_type) = UPPER(na.typecode) THEN 'exact_typecode'
        WHEN UPPER(s.icao_type) = 'DH4' AND na.typecode = 'DH8D' THEN 'iata_mapping'
        WHEN UPPER(s.icao_type) = 'J41' AND na.typecode = 'JS41' THEN 'iata_mapping'
        WHEN UPPER(s.icao_type) = 'CR2' AND na.typecode = 'CRJ2' THEN 'iata_mapping'
        WHEN UPPER(s.icao_type) = 'CR7' AND na.typecode = 'CRJ7' THEN 'iata_mapping'
        WHEN UPPER(s.icao_type) = '320' AND na.typecode = 'A320' THEN 'iata_mapping'
        WHEN UPPER(s.icao_type) = '319' AND na.typecode = 'A319' THEN 'iata_mapping'
        WHEN UPPER(s.icao_type) = '332' AND na.typecode = 'A332' THEN 'iata_mapping'
        WHEN UPPER(s.icao_type) = '752' AND na.typecode = 'B752' THEN 'iata_mapping'
        WHEN UPPER(s.icao_type) = 'BE1' AND na.typecode = 'B190' THEN 'iata_mapping'
        WHEN UPPER(s.icao_type) = 'D28' AND na.typecode IN ('D228', 'D28D') THEN 'iata_mapping'
        ELSE 'model_variant'
    END AS match_method,
    1.00 AS match_confidence,
    CASE
        WHEN s.model IN ('ATR72-500Basic', 'BombardierQ400', 'Jetstream41', 'DHC-6-400 Twin Otter', 'A320-200', '757-200', 'A330-200', 'BombardierCRJ200ER', 'BombardierCRJ700', 'Beech1900D', 'Dornier228-212', 'Let L-410 Turbolet', 'Airbus Helicopters H125 / AS350 B3', 'Bell 407GXP', 'Bell 505 Jet Ranger X', 'Leonardo AW139', 'ATR42-320Basic', 'A319-100') THEN TRUE
        ELSE FALSE
    END AS is_primary,
    CONCAT('Matched tail ', na.registration, ' (typecode: ', na.typecode, ') with spec ', s.model, ' [', s.icao_type, ']') AS notes
FROM public.nepal_aircraft na
JOIN public.aircraft_specifications s ON (
    -- 1. Exact ICAO code match
    UPPER(s.icao_type) = UPPER(na.typecode)
    -- 2. Precision model variant matching for Nepal carriers
    OR (na.typecode = 'AT75' AND s.model IN ('ATR72-500Basic', 'ATR72-500IncreasedWeight', 'ATR 72-500'))
    OR (na.typecode = 'AT43' AND s.model IN ('ATR42-320Basic', 'ATR42-320IncreasedWeight', 'ATR 42-320'))
    OR (na.typecode = 'DH8D' AND (s.icao_type = 'DH4' OR s.model ILIKE '%Q400%'))
    OR (na.typecode = 'JS41' AND (s.icao_type = 'J41' OR s.model ILIKE '%Jetstream41%'))
    OR (na.typecode = 'CRJ2' AND (s.icao_type = 'CR2' OR s.model ILIKE '%CRJ200%'))
    OR (na.typecode = 'CRJ7' AND (s.icao_type = 'CR7' OR s.model ILIKE '%CRJ700%'))
    OR (na.typecode = 'A320' AND (s.model IN ('A320-200', 'A320-200neo') OR s.icao_type = '320'))
    OR (na.typecode = 'A319' AND (s.model ILIKE '%A319%' OR s.icao_type = '319'))
    OR (na.typecode = 'A332' AND (s.model ILIKE '%A330-200%' OR s.icao_type = '332'))
    OR (na.typecode = 'B752' AND (s.model ILIKE '%757-200%' OR s.icao_type = '752'))
    OR (na.typecode = 'B190' AND (s.model ILIKE '%1900D%' OR s.icao_type = 'BE1'))
    OR (na.typecode IN ('D228', 'D28D') AND (s.model ILIKE '%228%' OR s.icao_type = 'D28'))
)
ON CONFLICT (nepal_aircraft_id, specification_id) DO NOTHING;

-- ------------------------------------------------------------------------------
-- 6. ROW LEVEL SECURITY (RLS) POLICIES
-- ------------------------------------------------------------------------------
ALTER TABLE public.nepal_aircraft ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.nepal_aircraft_specifications ENABLE ROW LEVEL SECURITY;

DO $$ 
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies WHERE tablename = 'nepal_aircraft' AND policyname = 'Allow public read on nepal_aircraft'
    ) THEN
        CREATE POLICY "Allow public read on nepal_aircraft" ON public.nepal_aircraft FOR SELECT USING (true);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_policies WHERE tablename = 'nepal_aircraft_specifications' AND policyname = 'Allow public read on nepal_aircraft_specifications'
    ) THEN
        CREATE POLICY "Allow public read on nepal_aircraft_specifications" ON public.nepal_aircraft_specifications FOR SELECT USING (true);
    END IF;
END $$;
