-- ==============================================================================
-- Nepal Flight Tracker - Nepal Registered Aircraft & Junction Schema
-- Target: Supabase (PostgreSQL 15+)
-- Tables:
--   1. public.nepal_aircraft (Nepal CAA civil aircraft registry dataset)
--   2. public.nepal_aircraft_specifications (Junction table linking Nepal aircraft to aircraft_specifications)
-- ==============================================================================

-- ------------------------------------------------------------------------------
-- 1. NEPAL AIRCRAFT TABLE
-- Stores full registry data for aircraft registered in Nepal (9N-xxx / NA-xxx).
-- Sourced from Nepal-aricraft-dataset.csv.
-- ------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.nepal_aircraft (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    icao24 VARCHAR(10) UNIQUE NOT NULL,                       -- 24-bit Mode-S transponder hex address (e.g. '70a00d')
    registration VARCHAR(20),                                 -- Nepalese tail registration mark (e.g. '9N-AIH', 'NA-058')
    typecode VARCHAR(10),                                     -- ICAO aircraft type designator (e.g. 'AT75', 'DH8D', 'A320', 'AS50')
    model TEXT,                                               -- Manufacturer/commercial model name (e.g. 'ATR 72-500', 'Dash 8-400')
    manufacturer_name TEXT,                                   -- Manufacturer name (e.g. 'Avions De Transport Regional', 'British Aerospace')
    manufacturer_icao TEXT,                                   -- Manufacturer ICAO identifier (e.g. 'ATR', 'AIRBUS', 'BOEING')
    operator TEXT,                                            -- Operating airline/company (e.g. 'Buddha Air', 'Yeti Airlines')
    operator_callsign TEXT,                                   -- Carrier telephony callsign (e.g. 'BUDDHA AIR', 'YETI AIRLINES')
    operator_icao VARCHAR(10),                                -- 3-letter ICAO carrier code (e.g. 'BHA', 'NYT', 'RNA')
    operator_iata VARCHAR(10),                                -- 2-letter IATA carrier code (e.g. 'U4', 'YT', 'RA')
    owner TEXT,                                               -- Legal owner/lessor (e.g. 'Buddha Air', 'Yeti Airlines')
    serial_number VARCHAR(50),                                -- Manufacturer Serial Number (MSN)
    icao_aircraft_class VARCHAR(10),                          -- ICAO aircraft class (e.g. 'L2T', 'L2J', 'H1T', 'H2T')
    category_description TEXT,                                -- Emitter / weight category description
    country VARCHAR(50) DEFAULT 'Nepal',                      -- Country of registration
    engines TEXT,                                             -- Installed powerplant description (e.g. 'PWC PW127F')
    built_year VARCHAR(20),                                   -- Year or date built
    first_flight_date DATE,                                   -- Date of maiden flight
    first_seen TIMESTAMPTZ,                                   -- First detected timestamp
    recorded_timestamp TIMESTAMPTZ,                           -- Snapshot timestamp
    registered_date DATE,                                     -- Date registered with Civil Aviation Authority of Nepal (CAAN)
    reg_until DATE,                                           -- Registration certificate expiry date
    status VARCHAR(50),                                       -- Operational / airworthiness status
    modes BOOLEAN DEFAULT FALSE,                              -- Mode-S transponder operational
    adsb BOOLEAN DEFAULT FALSE,                               -- ADS-B Out operational
    acars BOOLEAN DEFAULT FALSE,                              -- ACARS operational
    vdl BOOLEAN DEFAULT FALSE,                                -- VDL Mode 2 operational
    notes TEXT,                                               -- Additional operational notes or remarks
    sel_cal VARCHAR(20),                                      -- Selective Calling (SELCAL) code
    line_number VARCHAR(50),                                  -- Assembly line sequence number
    prev_reg VARCHAR(50),                                     -- Previous foreign registration mark
    next_reg VARCHAR(50),                                     -- Subsequent registration mark if exported
    created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc', NOW()) NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT TIMEZONE('utc', NOW()) NOT NULL
);

-- Indexes for high-frequency queries
CREATE INDEX IF NOT EXISTS idx_nepal_aircraft_icao24 ON public.nepal_aircraft (icao24);
CREATE INDEX IF NOT EXISTS idx_nepal_aircraft_reg ON public.nepal_aircraft (registration);
CREATE INDEX IF NOT EXISTS idx_nepal_aircraft_typecode ON public.nepal_aircraft (typecode);
CREATE INDEX IF NOT EXISTS idx_nepal_aircraft_operator ON public.nepal_aircraft (operator);
CREATE INDEX IF NOT EXISTS idx_nepal_aircraft_operator_icao ON public.nepal_aircraft (operator_icao);

-- ------------------------------------------------------------------------------
-- 2. SEED MISSING NEPAL-SPECIFIC AIRFRAME SPECIFICATIONS
-- Ensures STOL transports and mountain rescue helicopters active in Nepal
-- exist in public.aircraft_specifications before establishing junction links.
-- ------------------------------------------------------------------------------
INSERT INTO public.aircraft_specifications (
    model, icao_type, category, engine_type, engine_model, powerplant,
    number_of_engines, n_engine, passenger_capacity,
    oew_kg, owe, mtow_kg, mtow, mlw_kg, mlw, fuel_capacity_liters, max_fuel,
    cruise_speed_kts, max_speed_kts, cruise_altitude, nominal_range_nm,
    approach_speed_kts, takeoff_field_length_m, landing_field_length_m,
    fuselage_width, wing_span, wing_area, wing_position, total_length, total_height,
    thruster_type, energy_type, engine_position, max_power
)
SELECT * FROM (VALUES
    ('DHC-6-400 Twin Otter', 'DHC6', 'commuter', 'turboprop', 'PT6A-34', 'Pratt & Whitney Canada PT6A-34', 2, 2, 19, 3121.0, 3121.0, 5670.0, 5670.0, 5579.0, 5579.0, 1446.0, 1150.0, 150, 182, 25000.0, 775, 75, 366, 320, 1.750, 19.810, 39.020, 'high', 15.770, 5.940, 'propeller', 'kerosene', 'wing', 559.0),
    ('Let L-410 Turbolet', 'L410', 'commuter', 'turboprop', 'GE H80-200', 'General Electric H80-200', 2, 2, 19, 4050.0, 4050.0, 6600.0, 6600.0, 6400.0, 6400.0, 1625.0, 1300.0, 200, 224, 20000.0, 810, 82, 500, 480, 1.920, 19.980, 35.180, 'high', 14.490, 5.830, 'propeller', 'kerosene', 'wing', 597.0),
    ('Airbus Helicopters H125 / AS350 B3', 'AS50', 'helicopter', 'turboshaft', 'Safran Arriel 2D', 'Safran Arriel 2D', 1, 1, 6, 1318.0, 1318.0, 2250.0, 2250.0, 2250.0, 2250.0, 540.0, 426.0, 133, 155, 23000.0, 340, 60, 0, 0, 1.870, 10.690, 89.700, 'high', 12.940, 3.340, 'rotor', 'kerosene', 'fuselage', 632.0),
    ('Bell 407GXP', 'B407', 'helicopter', 'turboshaft', 'Rolls-Royce 250-C47B/8', 'Rolls-Royce 250-C47B/8', 1, 1, 6, 1221.0, 1221.0, 2381.0, 2381.0, 2381.0, 2381.0, 492.0, 388.0, 133, 140, 18000.0, 324, 60, 0, 0, 1.500, 10.670, 89.400, 'high', 12.700, 3.560, 'rotor', 'kerosene', 'fuselage', 606.0),
    ('Bell 505 Jet Ranger X', 'B505', 'helicopter', 'turboshaft', 'Safran Arrius 2R', 'Safran Arrius 2R', 1, 1, 4, 991.0, 991.0, 1669.0, 1669.0, 1669.0, 1669.0, 322.0, 254.0, 125, 135, 18610.0, 333, 55, 0, 0, 1.400, 11.280, 99.900, 'high', 12.930, 3.250, 'rotor', 'kerosene', 'fuselage', 377.0),
    ('Leonardo AW139', 'A139', 'helicopter', 'turboshaft', 'PT6C-67C', 'Pratt & Whitney Canada PT6C-67C', 2, 2, 15, 3622.0, 3622.0, 6400.0, 6400.0, 6400.0, 6400.0, 2088.0, 1645.0, 165, 167, 20000.0, 573, 65, 0, 0, 2.260, 13.800, 149.570, 'high', 16.660, 4.980, 'rotor', 'kerosene', 'fuselage', 1142.0)
) AS v(
    model, icao_type, category, engine_type, engine_model, powerplant,
    number_of_engines, n_engine, passenger_capacity,
    oew_kg, owe, mtow_kg, mtow, mlw_kg, mlw, fuel_capacity_liters, max_fuel,
    cruise_speed_kts, max_speed_kts, cruise_altitude, nominal_range_nm,
    approach_speed_kts, takeoff_field_length_m, landing_field_length_m,
    fuselage_width, wing_span, wing_area, wing_position, total_length, total_height,
    thruster_type, energy_type, engine_position, max_power
)
WHERE NOT EXISTS (
    SELECT 1 FROM public.aircraft_specifications s 
    WHERE s.icao_type = v.icao_type OR s.model = v.model
);

-- ------------------------------------------------------------------------------
-- 3. JUNCTION TABLE: nepal_aircraft_specifications
-- Connects individual Nepal registered airframes (tail numbers) with their
-- aerodynamic, engineering, weight, and performance specifications in aircraft_specifications.
-- ------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.nepal_aircraft_specifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nepal_aircraft_id BIGINT NOT NULL REFERENCES public.nepal_aircraft(id) ON DELETE CASCADE,
    specification_id BIGINT NOT NULL REFERENCES public.aircraft_specifications(id) ON DELETE CASCADE,
    match_method VARCHAR(50) DEFAULT 'typecode_match' NOT NULL, -- 'exact_typecode', 'model_variant', 'iata_mapping', 'manual_verified'
    match_confidence NUMERIC(3, 2) DEFAULT 1.00 NOT NULL,       -- Confidence score (0.00 - 1.00)
    is_primary BOOLEAN DEFAULT TRUE NOT NULL,                   -- Flag indicating the primary baseline specification
    notes TEXT,                                                 -- Detailed mapping / variant notes
    created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc', NOW()) NOT NULL,
    CONSTRAINT uq_nepal_aircraft_specification UNIQUE (nepal_aircraft_id, specification_id)
);

-- Indexes for junction lookups
CREATE INDEX IF NOT EXISTS idx_nas_nepal_aircraft_id ON public.nepal_aircraft_specifications (nepal_aircraft_id);
CREATE INDEX IF NOT EXISTS idx_nas_specification_id ON public.nepal_aircraft_specifications (specification_id);
CREATE INDEX IF NOT EXISTS idx_nas_composite ON public.nepal_aircraft_specifications (nepal_aircraft_id, specification_id);

-- ------------------------------------------------------------------------------
-- 4. ROW LEVEL SECURITY (RLS) POLICIES
-- Enables public read access for frontend and authenticated clients.
-- ------------------------------------------------------------------------------
ALTER TABLE public.nepal_aircraft ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.nepal_aircraft_specifications ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read on nepal_aircraft"
    ON public.nepal_aircraft FOR SELECT
    USING (true);

CREATE POLICY "Allow public read on nepal_aircraft_specifications"
    ON public.nepal_aircraft_specifications FOR SELECT
    USING (true);

-- ------------------------------------------------------------------------------
-- 5. AUTOMATIC POPULATION PROCEDURE FOR JUNCTION TABLE
-- Runs an intelligent match linking every possible Nepal aircraft to
-- its matching specification row(s) in aircraft_specifications.
-- ------------------------------------------------------------------------------
INSERT INTO public.nepal_aircraft_specifications (nepal_aircraft_id, specification_id, match_method, match_confidence, is_primary, notes)
SELECT 
    na.id AS nepal_aircraft_id,
    s.id AS specification_id,
    CASE 
        WHEN UPPER(s.icao_type) = UPPER(na.typecode) THEN 'exact_typecode'
        WHEN UPPER(s.icao_type) = 'AT7' AND na.typecode = 'AT75' THEN 'iata_mapping'
        WHEN UPPER(s.icao_type) = 'AT4' AND na.typecode = 'AT43' THEN 'iata_mapping'
        WHEN UPPER(s.icao_type) = 'DH4' AND na.typecode = 'DH8D' THEN 'iata_mapping'
        WHEN UPPER(s.icao_type) = 'J41' AND na.typecode = 'JS41' THEN 'iata_mapping'
        WHEN UPPER(s.icao_type) = 'CR2' AND na.typecode = 'CRJ2' THEN 'iata_mapping'
        WHEN UPPER(s.icao_type) = 'CR7' AND na.typecode = 'CRJ7' THEN 'iata_mapping'
        WHEN UPPER(s.icao_type) = '320' AND na.typecode = 'A320' THEN 'iata_mapping'
        WHEN UPPER(s.icao_type) = '319' AND na.typecode = 'A319' THEN 'iata_mapping'
        WHEN UPPER(s.icao_type) = '332' AND na.typecode = 'A332' THEN 'iata_mapping'
        WHEN UPPER(s.icao_type) = '752' AND na.typecode = 'B752' THEN 'iata_mapping'
        WHEN UPPER(s.icao_type) = 'BE1' AND na.typecode = 'B190' THEN 'iata_mapping'
        WHEN UPPER(s.icao_type) = 'D28' AND na.typecode IN ('D228', 'D28D') THEN 'iata_mapping'
        ELSE 'model_variant'
    END AS match_method,
    1.00 AS match_confidence,
    TRUE AS is_primary,
    CONCAT('Matched tail ', na.registration, ' (typecode: ', na.typecode, ') with specification ', s.model, ' [', s.icao_type, ']') AS notes
FROM public.nepal_aircraft na
JOIN public.aircraft_specifications s ON (
    -- 1. Exact ICAO code match
    UPPER(s.icao_type) = UPPER(na.typecode)
    -- 2. Standard ICAO/IATA designator cross-reference
    OR (na.typecode = 'AT75' AND s.icao_type = 'AT7' AND s.model ILIKE '%72-500%')
    OR (na.typecode = 'AT43' AND s.icao_type = 'AT4' AND s.model ILIKE '%42-320%')
    OR (na.typecode = 'DH8D' AND s.icao_type = 'DH4')
    OR (na.typecode = 'JS41' AND (s.icao_type = 'J41' OR s.model ILIKE '%Jetstream41%'))
    OR (na.typecode = 'CRJ2' AND s.icao_type = 'CR2')
    OR (na.typecode = 'CRJ7' AND s.icao_type = 'CR7')
    OR (na.typecode = 'A320' AND s.icao_type = '320')
    OR (na.typecode = 'A319' AND s.icao_type = '319')
    OR (na.typecode = 'A332' AND s.icao_type = '332')
    OR (na.typecode = 'B752' AND s.icao_type = '752')
    OR (na.typecode = 'B190' AND s.icao_type = 'BE1')
    OR (na.typecode IN ('D228', 'D28D') AND s.icao_type = 'D28')
)
ON CONFLICT (nepal_aircraft_id, specification_id) DO NOTHING;
